name: CI Build

on:
  push:
    branches: [ master ]   # or main, adjust based on your repo
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest   # Windows runner required for Web workloads

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Visual Studio Build Tools with Web workload
      - name: Install Visual Studio Build Tools (Web)
        run: choco install visualstudio2019-buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.WebBuildTools --quiet --norestart --includeRecommended --includeOptional" --yes
        shell: powershell

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --verbosity normal
