name: Build ASP.NET WebApp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup MSBuild (includes Microsoft.WebApplication.targets)
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # Setup NuGet
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      # Restore NuGet packages
      - name: Restore NuGet packages
        run: nuget restore Finc24.sln

      # Build with MSBuild (instead of dotnet build)
      - name: Build with MSBuild
        run: msbuild Finc24.sln /p:Configuration=Release /p:Platform="Any CPU"

      # Publish build artifacts (bin\Release)
      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WebApp-Build
          path: |
            **/bin/Release/**
