name: Build ASP.NET WebApp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup MSBuild (instead of dotnet build)
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # Optional: Setup NuGet
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      # Restore packages
      - name: Restore NuGet packages
        run: nuget restore Finc24.sln

      # Build solution with MSBuild
      - name: Build with MSBuild
        run: msbuild Finc24.sln /p:Configuration=Release
