ame: Build ASP.NET WebApp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print current directory
        run: pwd

      - name: List files and folders in current directory
        run: dir

      - name: Setup MSBuild (includes Microsoft.WebApplication.targets)
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
      
      - name: Change directory and restore NuGet packages
        shell: pwsh
        run: |
          cd Finc24
          nuget restore Finc24.sln
          cd ..

      - name: Build & Publish Web Project
        shell: pwsh
        run: |
          # The path is now relative to the Finc24 directory
          $projectPath = "Finc24/Finc24.Web/Finc24.Web.csproj"
          $publishPath = "publish"
          
          if (Test-Path $projectPath) {
            Write-Host "Found project file at $projectPath. Starting build..."
            
            # Run the msbuild command with detailed logging
            # The /v:d flag will print detailed errors and warnings to the log
            msbuild $projectPath /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:PublishUrl=$publishPath /v:d
            
            # Check if the publish directory was created successfully
            if (Test-Path $publishPath) {
              Write-Host "SUCCESS: Publish directory was created. The build completed."
              exit 0
            } else {
              Write-Host "ERROR: The 'publish' directory was not created after the build. Check the detailed log for errors."
              exit 1
            }
          } else {
            Write-Host "FATAL ERROR: Project file not found at $projectPath. This should not have happened."
            exit 1
          }
      - name: Upload Published Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WebApp-Published
          path: publish/**
