name: Build ASP.NET WebApp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print current directory
        run: pwd

      - name: List files and folders in current directory
        run: dir

      - name: List all files and folders recursively
        run: dir -Recurse .

      - name: List files in Finc24 folder (debugging)
        run: |
          if (Test-Path "Finc24") { dir Finc24 } else { Write-Host "Finc24 folder does not exist in this directory." }

      - name: Setup MSBuild (includes Microsoft.WebApplication.targets)
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore Finc24.sln

      - name: Build .NET project
        shell: pwsh
        run: |
          # Find the first .csproj file dynamically
          $projectPath = Get-ChildItem -Path . -Recurse -Filter *.csproj | Select-Object -First 1 -ExpandProperty FullName
          
          if (Test-Path $projectPath) {
            Write-Host "Found project file at $projectPath. Starting build..."
            msbuild $projectPath /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:PublishUrl="publish"
          } else {
            Write-Host "ERROR: No .csproj file found in repository."
            exit 1
          }

      - name: Upload Published Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WebApp-Published
          path: publish/**
